export const SET_SERVICES = "SET/SERVICES";
export const SET_PARFUME = "SET/PARFUME";
export const SET_TREATMENT = "SET/TREATMENT";
export const SET_STATUS_LOGIN = "SET/STATUS/LOGIN";
export const SET_ACCESS_TOKEN = "SET/ACCESS/TOKEN";
